/**
 * Action Definitions below. Actions should be named ACTION_<NAME> where
 * <NAME> is a noun describing an event that happened (past tense).
 */
export const ACTION_TYPE_SELECTED_LISTING_CHANGED = 'SET_CURRENT_LISTING'
export const ACTION_TYPE_SELECTED_APPLICATION_CHANGED = 'SET_CURRENT_APPLICATION'

export const ACTION_TYPE_LEFT_LISTING_SCOPE = 'CLEAR_CURRENT_LISTING'
export const ACTION_TYPE_LEFT_APPLICATION_SCOPE = 'CLEAR_CURRENT_APPLICATION'

export const ACTION_TYPE_SUPP_APP_LOADED = 'SUPP_APPLICATION_LOADED'
export const ACTION_TYPE_SHORTFORM_LOADED = 'SHORTFORM_APPLICATION_LOADED'

export const ACTION_TYPE_APPLICATION_TABLE_FILTERS_APPLIED = 'APPLICATION_TABLE_FILTERS_APPLIED'
export const ACTION_TYPE_APPLICATION_TABLE_PAGE_CHANGED = 'APPLICATION_TABLE_PAGE_CHANGED'
