/**
 * Action Definitions below. Actions should be named like a
 * past-tense event.
 */
export default {
  // Lease-up navigation actions
  SELECTED_LISTING_CHANGED: 'SELECTED_LISTING_CHANGED',
  SELECTED_APPLICATION_CHANGED: 'SELECTED_APPLICATION_CHANGED',
  LEFT_LISTING_SCOPE: 'LEFT_LISTING_SCOPE',
  LEFT_APPLICATION_SCOPE: 'LEFT_APPLICATION_SCOPE',

  // ApplicationDetails Actions
  SUPP_APP_LOAD_START: 'SUPP_APP_LOAD_START',
  SUPP_APP_LOAD_SUCCESS: 'SUPP_APP_LOAD_SUCCESS',
  SUPP_APP_LOAD_FAIL: 'SUPP_APP_LOAD_FAIL',
  SUPP_APP_LOAD_COMPLETE: 'SUPP_APP_LOAD_COMPLETE',
  SHORTFORM_LOADED: 'SHORTFORM_LOADED',
  STATE_UPDATED: 'STATE_UPDATED',
  LEASE_AND_ASSISTANCES_UPDATED: 'LEASE_AND_ASSISTANCES_UPDATED',
  RENTAL_ASSISTANCE_CREATE_SUCCESS: 'RENTAL_ASSISTANCE_CREATE_SUCCESS',
  RENTAL_ASSISTANCE_DELETE_SUCCESS: 'RENTAL_ASSISTANCE_DELETE_SUCCESS',
  RENTAL_ASSISTANCE_UPDATE_SUCCESS: 'RENTAL_ASSISTANCE_UPDATE_SUCCESS',
  STATUS_MODAL_UPDATED: 'STATUS_MODAL_UPDATED',
  CONFIRMED_PREFERENCES_FAILED: 'CONFIRMED_PREFERENCES_FAILED',

  // Applications List Page actions
  APPLICATION_TABLE_FILTERS_APPLIED: 'APPLICATION_TABLE_FILTERS_APPLIED',
  APPLICATION_TABLE_PAGE_CHANGED: 'APPLICATION_TABLE_PAGE_CHANGED'
}
