version: "2"
exclude_patterns:
  - "lib/assets"
  # code climate complains a bunch about our toolkit.css -- is it useful to validate our CSS?
  - "app/assets/stylesheets"
  # complaints in specs have mostly been duplication (erroneously), but only global exclusion is supported by code climate
  - "spec"
  # test data
  - "spec/javascript/fixtures"
  # cypress tests have a lot of duplicate code due to setting up fixtures
  - "cypress"
checks:
  method-complexity:
    config:
      threshold: 8
engines:
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 100
        javascript:
          mass_threshold: 100
