version: "2"
exclude_patterns:
  - "lib/assets"
  # code climate complains a bunch about our toolkit.css -- is it useful to validate our CSS?
  - "app/assets/stylesheets"
  # duplication complaints in API specs are caused by similar endpoint headers and test names, despite controllers being different
  - "spec/controllers/api"
  # test data
  - "spec/javascript/fixtures"
checks:
  method-complexity:
    config:
      threshold: 8
engines:
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 100
        javascript:
          mass_threshold: 100
