// import { mapShape, mapList } from './utils'
export { mapApplicationPreference } from './soqlToDomain/application_preference'
export { mapFormApplication } from './soqlToDomain/application'
export { mapListingDetails } from './soqlToDomain/listing'
export { mapFlaggedApplication } from './soqlToDomain/flagged_application'
export { mapFlaggedRecord } from './soqlToDomain/flagged_record'
export { mapFieldUpdateComment } from './soqlToDomain/field_update_comment'
