---
http_interactions:
- request:
    method: post
    uri: https://<<SALESFORCE_HOST>>/services/oauth2/token
    body:
      encoding: US-ASCII
      string: grant_type=password&client_id=<<SALESFORCE_CLIENT_ID>>&client_secret=<<SALESFORCE_CLIENT_SECRET>>&username=<<SALESFORCE_USERNAME>>&password=<<SALESFORCE_PASSWORD>><<SALESFORCE_SECURITY_TOKEN>>
    headers:
      User-Agent:
      - Faraday v2.7.4
      Content-Type:
      - application/x-www-form-urlencoded
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Wed, 01 May 2024 00:18:54 GMT
      Set-Cookie:
      - BrowserId=ZRP3QgdQEe-rxkOTQfPpmA; domain=.salesforce.com; path=/; expires=Thu,
        01-May-2025 00:18:54 GMT; Max-Age=31536000
      - CookieConsentPolicy=0:1; path=/; expires=Thu, 01-May-2025 00:18:54 GMT; Max-Age=31536000;
        secure
      - LSKey-c$CookieConsentPolicy=0:1; path=/; expires=Thu, 01-May-2025 00:18:54
        GMT; Max-Age=31536000; secure
      Strict-Transport-Security:
      - max-age=63072000; includeSubDomains
      X-Content-Type-Options:
      - nosniff
      X-Robots-Tag:
      - none
      Cache-Control:
      - no-cache,must-revalidate,max-age=0,no-store,private
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      X-Readonlymode:
      - 'false'
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '{"access_token":"<<ACCESS_TOKEN>>","instance_url":"https://<<SALESFORCE_HOST>>","id":"https://test.salesforce.com/id/00D8H0000004dNlUAI/005U00000066jl9IAA","token_type":"Bearer","issued_at":"1714522734811","signature":"9yQqzdqCSK4G5Qh5V58Z5Ogxx+6OLFCWoMw7GOf+Bh4="}'
  recorded_at: Wed, 01 May 2024 00:18:54 GMT
recorded_with: VCR 6.1.0
