---
http_interactions:
- request:
    method: post
    uri: https://<<SALESFORCE_HOST>>/services/oauth2/token
    body:
      encoding: US-ASCII
      string: grant_type=password&client_id=<<SALESFORCE_CLIENT_ID>>&client_secret=<<SALESFORCE_CLIENT_SECRET>>&username=<<SALESFORCE_USERNAME>>&password=<<SALESFORCE_PASSWORD>><<SALESFORCE_SECURITY_TOKEN>>
    headers:
      User-Agent:
      - Faraday v2.7.4
      Content-Type:
      - application/x-www-form-urlencoded
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 307
      message: Temporary Redirect
    headers:
      Date:
      - Tue, 28 Nov 2023 23:48:36 GMT
      Set-Cookie:
      - BrowserId=peDZ545IEe6x6w8SjeXdXw; domain=.salesforce.com; path=/; expires=Wed,
        27-Nov-2024 23:48:36 GMT; Max-Age=31536000
      - CookieConsentPolicy=0:1; path=/; expires=Wed, 27-Nov-2024 23:48:36 GMT; Max-Age=31536000
      - LSKey-c$CookieConsentPolicy=0:1; path=/; expires=Wed, 27-Nov-2024 23:48:36
        GMT; Max-Age=31536000
      Strict-Transport-Security:
      - max-age=63072000; includeSubDomains
      X-Content-Type-Options:
      - nosniff
      Content-Security-Policy:
      - upgrade-insecure-requests
      X-Robots-Tag:
      - none
      Cache-Control:
      - no-cache,must-revalidate,max-age=0,no-store,private
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Location:
      - https://sfhousing--full.sandbox.my.salesforce.com/services/oauth2/token
      Transfer-Encoding:
      - chunked
    body:
      encoding: UTF-8
      string: "The URL has moved <a href=\"https://sfhousing--full.sandbox.my.salesforce.com/services/oauth2/token\">here</a>\r\n"
  recorded_at: Tue, 28 Nov 2023 23:48:36 GMT
- request:
    method: post
    uri: https://sfhousing--full.sandbox.my.salesforce.com/services/oauth2/token
    body:
      encoding: US-ASCII
      string: grant_type=password&client_id=<<SALESFORCE_CLIENT_ID>>&client_secret=<<SALESFORCE_CLIENT_SECRET>>&username=<<SALESFORCE_USERNAME>>&password=<<SALESFORCE_PASSWORD>><<SALESFORCE_SECURITY_TOKEN>>
    headers:
      User-Agent:
      - Faraday v2.7.4
      Content-Type:
      - application/x-www-form-urlencoded
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 400
      message: Bad Request
    headers:
      Date:
      - Tue, 28 Nov 2023 23:48:37 GMT
      Set-Cookie:
      - BrowserId=piRyjY5IEe6nxEkZQAWIyg; domain=.salesforce.com; path=/; expires=Wed,
        27-Nov-2024 23:48:37 GMT; Max-Age=31536000
      - CookieConsentPolicy=0:1; path=/; expires=Wed, 27-Nov-2024 23:48:37 GMT; Max-Age=31536000
      - LSKey-c$CookieConsentPolicy=0:1; path=/; expires=Wed, 27-Nov-2024 23:48:37
        GMT; Max-Age=31536000
      Strict-Transport-Security:
      - max-age=63072000; includeSubDomains
      X-Content-Type-Options:
      - nosniff
      X-Robots-Tag:
      - none
      Cache-Control:
      - no-cache,must-revalidate,max-age=0,no-store,private
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      X-Readonlymode:
      - 'false'
      Content-Type:
      - application/json;charset=UTF-8
      Transfer-Encoding:
      - chunked
    body:
      encoding: UTF-8
      string: '{"error":"invalid_grant","error_description":"authentication failure"}'
  recorded_at: Tue, 28 Nov 2023 23:48:37 GMT
- request:
    method: post
    uri: https://sentry.io/api/1438051/store/
    body:
      encoding: US-ASCII
      string: eJztXXtz2ziS/ypc7x+xq6IX9bClnb2b3Ez2au4yt7NJZra25lIsiAQlxBTBAUnJSsr32a+7AVKgXn7JjBLblYfVBIHuXz8BAtTnEx7PhZLxjMfZyegk42l28vKEz+GjJwKgDId+vxucu+cX7XbP7Q2Hg9Dl4fjinA+GQeieY+urTLGT0eeTlKs5V/ibTPHfmM04dPEjUwsRQ0O4mAoZlyTnv7mKeeT8pumO2212mu2R8zP8/nc/c5yh43ZG7sWo13d++fG947bd7l8cJWU2uorzRqfdbrvNXqc5/L9B6+3rN69fvXvtvXr786DnvR+03TaMOM5FhFLonoFwSSN6dXNy/fJE5XEmEI8SF5WPlxVUkODgyN2kc9F3TmEUt9HpNNyeo/hcEGcdNhh3Buf9AT9zfmdqNug1AhLBdT+cXF/DQBFoL4LeuFJSQf+RnExQK8V4MxnkEScFKXaJjHS6zXZzAJd8Gfu5UqD8BjWGS0236cIV0bmI6WPHJRxnIhZkLKOTfrNzQbTsk4hDiWib7j5xkS24uiTSoIm2wvxMzHmaJ4lUePMApD1vdgtVEZ9dGLOHdgU8iPVBPbxRRNylTi+aHaAr5vvUbkC8xvJSToQyt/aod8VElDYCOWsg1yKeGDbxmq9YmlJjzXYkZcim1MBt08D67mk2ixopA8HFJ2K00+zTZRRKgh/xRUUiYEuLjsL3DKFhUHONQep7E910dW8sZE9Rs35zCJ8XfJxK/5JnDfA2HqMpIMttuKFfuRwoQT4Il87pkh7AZ+OIV0aYRHLMIvLxjsXLnH+U40pDTQWrIatapyvuSxVULsyY8qktAuoWepuR8dNY7soQMqnYpMpYwDJOVtClj+g0Ms9Ioq7WL4iZKJlJX0ZEdskKkCxmLDEte0VLmRiginvTWVY00uyKyDImjRcSx/JqQ2B9hQBev5CBZirkJB9HwvfSPAzFFTlKW48QBIqnqdEIjou8MmMWPQ3Pgqdyxr1ECQrMEFqIPvbVMskIHkDygnwWvIYtDbTkSTzLuPLI/1Pqc0jjjkUc8CuSXIsa8HE+8UScJtwHRViWgE3BSTwZej6LImPt2hnGeRxoimtAHS+xI2xSsDBjmRJ6KC2P4hN+lXgJU6m59Zw6u0pYNjU+j599lizHDNMJGsBQ06YQGUDhPic37Ro+UupQk4n5XrMzILkQEo/FLFp+Mq7QJ1fwZRhy3kh9JRIwA5mDnRbxxaVExv2PqWULlRuMdpA+49lUBp7Vg2YJqMoEzY4JG5nAUGtZhemTQgox7RqArmaRAaKvgxKFBASwr3XFUk5h2QOP46vBC+h0C+MQ/SZYAcOOpZp5LGBJVkJBEY2niQRzUKmxJSQumAp4bAQYUpeQdThxqc0vEGHYiPzUCn6B9EWkQegZAgSouYWiJpQSF2QK76llCyHzeWbzE4IhBGzZAKf1phk5bdeEFMTB9S75cgHRR0fCNuFk7jHd9qxeQhlFcuEpHggIWllqQgAllhz0BLaJ0cK4YbfCQdnAKJv6DU2G0cY1ZekU4TEtOoYkuPF87A7iIHmABd/HVd4Do9HR/GNK5QCmDbSYj4vMQkmNG2FKBZoOa9oFgSpimYlwqamagUikGSkUYbsoBPW0pUGyow5jvlAcA5VKZljwGfBNWeJN+MwK22nMLpceCmYSKA4jWZ5NXUNAu5EftRZ17pWzWGALK4wVpEZ5a+Ee5RUyF89PVYhOnnGKsVYkLxumDKqZUK48ESGUwL4vZzOhURpo/AF8jGY6N7naScuQhH6kPSmZGHPGaiBRBtKubq6WjTLedZs6QiGxMG+0KcQgSZf+1OSxHmWDGaNAUMQGqAVAsKulydU4Vorh7LJwgnONeEErR+gWMdV8tisOrFOgisuUxKhtFTsFMBpWqtS9NGMZ6B2qH57ZPmTaZAHkXQ/LR91F9XLHBX/VWaNtCinF/8jBtzzA2IrT6Koo6QSTHsR2bU3dVWHljYFLUDKmUZ/r2OJ2VyJ6EVvqCoBcz9DjsVwUeVAHtKwwgkERUzGxNVbFZrcoJPUFDKMFtVNSIauArbHMVFjdIjnoqzPQRUnul+RVNC/DE1QnSUMndRBHV8h5LDA3NQKRJiCUtxBBNrWyvrlNhwftW4QeJeqGCLixla658EkkJliRpYAiG6XL94o0ydLCnHpUTkV2+Un3FNz3C6KPimcUDvqmSkp5xGORzxpQapY1Jrq4S3V9ymcsRmNSLJ7wSpYGY0TvmJtAZOKImCURlI5zqqqLmFW5oonnhELGkVg0o34jMbNZho+WgwwK1ykqfW0kmtBYsMyfgneUWBWBLP0jgllN92Q1l8gnkQgFVyZTU2D0i+qPciYfo8OlMuJWG6CipWiBdboDElb51FUf9N2zaQ3FwfpPihoXZnFgH2jPKKOZt0GQ5jrBB912p88oYASX9oQSQW5sTCs15tcvzfzcM63f//Su8c9/tf/x5p9vekMyDTbBWeG1rrkhOMzIumCqS5PQi/dud9S7GHVR3zDjj1NWxORXiRiNfuuMRm+Qw1+TV0kCCUX70A9lNPqzrj8BVAq4OBC/8nmiO/l8MmdRju7/++eTbJkgi28Lpx6NXkGo52hh1OtrM7elW6ChiOc4l/EmwFY2clilsROCXeSKO6e9dvvspJgB2/0jlBloAsTyaYoeKgBJ88LGqWeq1FXccE512DhzoGhsER1LgjwuIPkO5gnxv1EOjnkMs+Iepn9wKsA0ZFHKMWvIjxBqPFxGgDtavwIsaQskihhUb+k0560fpZ/j0kzagjrnMgVj4a00hBn/NBKsEcFkBwaF8qswgL38Xb+8UZhIjHXjFtJbKo9jrppqXJUN0JaX3Jat/4WE28nvwWQFsiXoeeeJCHox/JYF9bBRaonb6XwLFsyxztkmMV2wzfhLBaM9HB9Mv+MIMq8jYme7ogdHIvoDFA31RigmuaLstiH/QmRTL82hkPGmUl7a0rvt8/ZxiL8hwoHVf+o6tA6enu20BPfbjeUzYuMpSGq03X0S2uZXDKdBUOXKPLkhgQ/aF8ch8AbTh5a7auxPR247zz1JANblPn86cnumhR3iBj33iQCw5vFPRu5KZbvVAo6kuD0cEjc4vds/knmqxe7hZKVKngGGceAx+JuKeBLxTMaerx83bxT4/c6RlDmPjkdhYusI9AbHlf7uhwBJdYPt9y6OxNtLZg8o51Y1e6He0FSEO/dInP8BAOwyddx1YYna7R9XjjuktndN2G9lAUfi7Ad3AdyKkmfcw5Bn28HwSNZvHsHkRZxmLPa5h7JXHi4cV2H/LLWR2jzkpDsvijsNUfdwK1//LpOJc2r2DgRn9jOzbh0Y3E6M59D+HNqfQ/vTC3JPWWraT+Oc0qYm+2ait8ym0tt5/Xd6z8XoZ3Nu4I0Iub/0I/5K92JH/fP6nsXeXsLn+P8c/5/j/1ONhE9T6v3R0dzdWm039jbWfW+dF1a7BF/rPv4Tu7CzQmdY39LmwwV/Thf3Thd3yRHf6grojme738KS7y47L0V+Oqv8d4Li+QHQTrdwB91vWOhdZcRXILVpU6RJ4CQRrXmnRQcZvDxB3suDAp6VT/ctHnZvuXjY2QYPLzznZPT7yf+iETlOwPGA55g7L/QJhRdOIM0lxxGZ80LxLFdx6sg4Wjo2y+SgDvQacsVBRUCYwm8WBc9C0YELB/x3nR5JPKi7xDMzlw6/Emlmhv5AR/HJwVEakN2hn99+eNvMATmfjmxl/PRFBdFGniDEK/5enBWi4LlGW3TH/OCJuFnq/NX5XEqsf/BsDJ4AFsHIKdVliC/X2iZswkdO+6Xm/PA2+GAzWjPLua+cUzrAo20ZPm8Ymw1zpQqtY+v0DgZvFqOVZyJqzZkSeLocUsck9chtzDHurdWlbmEJWcdj1XsyX0eA6d02wGyrQfg2L7u3O63I13vCguNMeOaMKHi9NC49Mv/v8X4eB9YQ+tzjqT4YnvKzZiadKZtzOnlNR0Xz9HSU5j6etz+zbsTTyhBA/uvd3/+nSYdpyz6aYxksz76WqLDr8KxzSmdnTdqjGeCqUcs0agkAd7JjR/6+ie9Pq/sqtlVLoX9IidfQXL3XRLv5ebOr+9MXvLUOMdZulj5g1pUVsjqK/vsyvia/fnUCriEMizUETaK77LWDKY+SbcvoxRsv7Ll/DfLfi/GDCw+wZv7UM2+ksPyiXUf+PQ4MCIInKns50/uKveBh4ZWOvLOM0+sZFCWxW4SIQS2rg48h2GPkj018esM6itsD5ZBDYmAXQEV9Zq8bXdTx9Kl+XGY8Y9EGJvj+jfXgWsvjt/twvlV4fNnc9i7wSktxfLcTeNttqor6POIuXN9a5+MU39qQ2diNbxcMOoM6Usm9ON8iffGuvS0AwixNX2sVrxyzM5R58+TOyGBe42GtLNbxfPJQIj0wNrT0NNlbKBB3ywLJbpB6R5ZJdonzUIBw/VkRz9tntzsR6taxPn0IcbY6m3lt1HbTNBdb9Mq1Yo1h68q9Hsq2m3ZdsNxXhgPBYSG99R0y27CpY4JzMHkey2zKuc+3Yz8HDTjrc8MtkacuO3qEyHOnLqGS9/O7ZPY6pocPkOIhRR8+JBhD053T5E04enU8LL+/EPcPMLuxwK015dXK09L6ir67i/AYSFR2G22FpJbtRccEya6tBl8VEvYbJ2nPQrmHDyn2Y4t0Y5HKs95ruC8v+1Ee8MBCqA7nOaRgX8ahOl9ZjDlA7rm5WKnl9RUHTUJ3TO43LEVtKd+OcSmuntWpbSXbl33qebdFqjshCv0I38P3/QpfgDQE8AYyEPaCTVjqSkiHEWgdqSS5z86FLflav1B3SxaCmca2/Sh/dugVvc6viWO/pNdZDeKEUjmMdnk4c8GcbMqdV7/8ZDZ8+BED+t7X/DrfQddi9bncKhLw0CGO92xlqeyu+6uTyj8iz9o1h28wFj5vQjOLTPvCi900pzaKiDiuh53t2QZjD/n7SC86ph9g8L/pNw//Uo7ThHvnXGU01On2+146o1DJmbd6Kz1QMukFEl8IrPmwNs9oE6E9NKMKJ4+1a+YBpvdIRrxDxzs2w+ywawfyq5izjFcBRpPb0f8eIzSKfwc32up/Z4wv5otT8zVJHr7KerdxFTusKvxss8+no20A71mzR6dZg1zaooi1vULBk7uCReJTxTU7NypQp4z/gC7XMkHR3ekKaq2l75EAARj/26PM7/1IAGDQ8Af65W/0fRRL0iJ12aTvVtkT+r8H1FaBHrIW3Wv6XXFkKfvRdLlDAzfrSjPrhUb4jfkHfQOePZW/QWEVJa0A1ICJ0HmLM8smj+dNfET/73u3pQKadMzVo6958TJ5yePTV1RbvMffm7ivFh/0Y0O6ui9R88gyoZ3dk/E0LYptWVqTdSlxUzU3q1NXXprzzcW7dbju5ol6y6ljKaAaTnkUbmrEQq/0t/LLVjxN2mMEukHT+kYG/qc9OjbNZWLKKkuPH76kP66rZX2rVwEIThTccl2moGKk9rmKga3KN1NsKLgCU2V1to5tXfcX4o5wzEQQRHzBFL8vIN1ajrk9RIzrD9f45/8BaG7N/g==
    headers:
      User-Agent:
      - sentry-ruby/3.1.2
      Content-Type:
      - application/octet-stream
      X-Sentry-Auth:
      - Sentry sentry_version=5, sentry_client=raven-ruby/3.1.2, sentry_timestamp=1701215317,
        sentry_key=220b63fca88041809b887a91c5f3701d
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - nginx
      Date:
      - Tue, 28 Nov 2023 23:48:37 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '41'
      Access-Control-Allow-Origin:
      - "*"
      Vary:
      - origin,access-control-request-method,access-control-request-headers
      Access-Control-Expose-Headers:
      - x-sentry-error,x-sentry-rate-limits,retry-after
      Cross-Origin-Resource-Policy:
      - cross-origin
      X-Envoy-Upstream-Service-Time:
      - '0'
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains; preload
      Via:
      - 1.1 google
      Alt-Svc:
      - h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
    body:
      encoding: UTF-8
      string: '{"id":"99c53d727800424996f2efb87e69df27"}'
  recorded_at: Tue, 28 Nov 2023 23:48:37 GMT
recorded_with: VCR 6.1.0
