---
http_interactions:
- request:
    method: post
    uri: https://<<SALESFORCE_HOST>>/services/oauth2/token
    body:
      encoding: US-ASCII
      string: grant_type=password&client_id=<<SALESFORCE_CLIENT_ID>>&client_secret=<<SALESFORCE_CLIENT_SECRET>>&username=<<SALESFORCE_USERNAME>>&password=<<SALESFORCE_PASSWORD>><<SALESFORCE_SECURITY_TOKEN>>
    headers:
      User-Agent:
      - Faraday v2.7.4
      Content-Type:
      - application/x-www-form-urlencoded
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 307
      message: Temporary Redirect
    headers:
      Date:
      - Wed, 29 Nov 2023 21:31:47 GMT
      Set-Cookie:
      - BrowserId=s1YD_I7-Ee6pfeePEyOT0g; domain=.salesforce.com; path=/; expires=Thu,
        28-Nov-2024 21:31:47 GMT; Max-Age=31536000
      - CookieConsentPolicy=0:1; path=/; expires=Thu, 28-Nov-2024 21:31:47 GMT; Max-Age=31536000
      - LSKey-c$CookieConsentPolicy=0:1; path=/; expires=Thu, 28-Nov-2024 21:31:47
        GMT; Max-Age=31536000
      Strict-Transport-Security:
      - max-age=63072000; includeSubDomains
      X-Content-Type-Options:
      - nosniff
      Content-Security-Policy:
      - upgrade-insecure-requests
      X-Robots-Tag:
      - none
      Cache-Control:
      - no-cache,must-revalidate,max-age=0,no-store,private
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Location:
      - https://sfhousing--full.sandbox.my.salesforce.com/services/oauth2/token
      Transfer-Encoding:
      - chunked
    body:
      encoding: UTF-8
      string: "The URL has moved <a href=\"https://sfhousing--full.sandbox.my.salesforce.com/services/oauth2/token\">here</a>\r\n"
  recorded_at: Wed, 29 Nov 2023 21:31:47 GMT
- request:
    method: post
    uri: https://sfhousing--full.sandbox.my.salesforce.com/services/oauth2/token
    body:
      encoding: US-ASCII
      string: grant_type=password&client_id=<<SALESFORCE_CLIENT_ID>>&client_secret=<<SALESFORCE_CLIENT_SECRET>>&username=<<SALESFORCE_USERNAME>>&password=<<SALESFORCE_PASSWORD>><<SALESFORCE_SECURITY_TOKEN>>
    headers:
      User-Agent:
      - Faraday v2.7.4
      Content-Type:
      - application/x-www-form-urlencoded
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 400
      message: Bad Request
    headers:
      Date:
      - Wed, 29 Nov 2023 21:31:47 GMT
      Set-Cookie:
      - BrowserId=s4isg47-Ee6xx3NdilDezQ; domain=.salesforce.com; path=/; expires=Thu,
        28-Nov-2024 21:31:47 GMT; Max-Age=31536000
      - CookieConsentPolicy=0:1; path=/; expires=Thu, 28-Nov-2024 21:31:47 GMT; Max-Age=31536000
      - LSKey-c$CookieConsentPolicy=0:1; path=/; expires=Thu, 28-Nov-2024 21:31:47
        GMT; Max-Age=31536000
      Strict-Transport-Security:
      - max-age=63072000; includeSubDomains
      X-Content-Type-Options:
      - nosniff
      X-Robots-Tag:
      - none
      Cache-Control:
      - no-cache,must-revalidate,max-age=0,no-store,private
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      X-Readonlymode:
      - 'false'
      Content-Type:
      - application/json;charset=UTF-8
      Transfer-Encoding:
      - chunked
    body:
      encoding: UTF-8
      string: '{"error":"invalid_grant","error_description":"authentication failure"}'
  recorded_at: Wed, 29 Nov 2023 21:31:48 GMT
- request:
    method: post
    uri: https://sentry.io/api/1438051/store/
    body:
      encoding: US-ASCII
      string: eJztXXtz2ziS/ypc7R+xq6IHqZelnb2b3Ez2au4yt7NJZra25lIsiIQkxBTBAUnJSsr32a+7AVLQ0y+ZUWK78rCaIND96ydAgPpc4/FcKBnPeJzVhrWMp1ntZY3P4aMvQqD0eL81YIOR5/Gw0+/0Btxth32XB/0eC3peB1tfZYrVhp9rKVdzrvA3meK/MZtx6OJHphYihoZwMRUyLknOf3MV88j5TdMdr91wG62h8zP8/vcgc5yB47lD72LY6Tq//Pje8Vpe+y+OkjIbXsV53W21Wl6j4zYG/9drvn395vWrd6/9V29/7nX8972W14IRR7mIUArdMxAuaUS/ak6uX9ZUHmcC8ShxUflouYYKEhwcuZ24F13nDEbx6q5b9zqO4nNBnLmsN3J7/W6Pnzu/MzXrdeohieB5H2rX1zBQBNqLoDeulFTQfyQnE9RKMd5MhnnESUGKXSIjbrvRavTgUiDjIFcKlF+nxnCp4TU8uCLci5g+uh7hOBOxIGMZ1roN94Jo2ScRjyWibbr7xEW24OqSSL1GH0gsyMScp3mSSIU390DafqNdqIr4bMOYZFfAg9gc1McbRcQ96vSi4QJdsSCgdj3iNZaXciKUubVDvSsmorQeylkduRbxxLCJ1wLF0pQaa7YjKcdsSg28Fg2s755ms6ieMhBcfCJG3UaXLqNQEvyIL9YkAra06Ch8xxDqBjXPGKS+N9FNV/fGQnYUNes2BvB5wUepDC55Vgdv4zGaArLcghu6a5dDJcgH4VKfLukBAjaK+NoIk0iOWEQ+7lq8zPlHOVprqKlgNWRVm3TFA6nCtQszpgJqi4B6hd5mZPw0lrcyhEwqNllnLGQZJyto00d0GplnJFFb6xfETJTMZCAjIntkBUgWM5aYlp2ipUwMUMW96SwrGml2RWQZk8YLiSN5tSWwvkIAb17IQDNr5CQfRSLw03w8FlfkKC09QhgqnqZGIzgu8sqMWXQ0PAueyhn3EyUoMENoIfooUMskI3gAyQvyWfAatjTQkifxLOPKJ/9Pqc8BjTsSccivSHItashH+cQXcZrwABRhWQI2BSfx5dgPWBQZa9fOMMrjUFM8A+poiR1hk4KFGcuU0ENpeRSf8KvET5hKza196uwqYdnU+Dx+DliyHDFMJ2gAA02bQmQAhQec3LRt+EipQ00m5jsNt0dyISQ+i1m0/GRcoUuuEMjxmPN6GiiRgBnIHOy0iC8eJTIefEwtW1i7wWgH6TOeTWXoWz1oloCqTNB0TdjIBIZayypMnxRSiGnPAHQ1iwwQXR2UKCQggF2tK5ZyCss+eBxfDV5Ap1sYh+g2wAoYdizVzGchS7ISCopoPE0kmINKjS0hccFUyGMjwIC6hKzDiUttfqEYj+tRkFrBL5SBiDQIHUOAADW3UNSEUuKCTOE9tWxhzAKe2fyMwRBCtqyD0/rTjJy2bUIK4uD5l3y5gOijI2GLcDL3mG47Vi9jGUVy4SseCghaWWpCACWWHPQEtonRwrhhe42DsoFRNvU7NhlGG9eUpVOEx7RwDUlw4/nYHcRB8gALvo+rvAdGo6P5x5TKAUwbaDEfF5mFkhrVxykVaDqsaRcEqohlJsZLTdUMRCLNSKEI20UhqK8tDZIddRjzheIYqFQyA/LAgG/KEn/CZ1bYTmN2ufRRMJNAcRjJ8mzqGQLajfyotahzr5zFAltYYawg1ctbC/cor5C5+EGqxujkGacYa0XysmHKoJoZy5UnIoQS2A/kbCY0Sj2NP4CP0UznJk87aRmS0I+0JyUTY85YDSTKQNrWzdWyXsa7dkNHKCQW5o02hRgk6TKYmjzWoWwwYxQIitgAtQAIdrU0uRrHSjGcXRZO0NeIF7RyhHYRU81nu+LAOgWquExJjNpWsVMAo2GlSt1PM5aB3qH64ZntQ6ZNFkLe9bF81F2sX3Y98FedNVqmkFL8jxx8yweMrTiNroqSTjDpQWzX1tReFVb+CLgEJWMaDbiOLV57JaIfsaWuAMj1DD0eyUWRB3VAywoj6BUxFRNbfVVstotCUl/AMFpQ3ZIKWQVsjWWmwmoXyUFfnYEuSnK3JK+ieRmeoDpJ6jqpgzi6Qs5jgbmpHoo0AaH8hQizqZX1zW06PGjfIvQoUddFyI2ttM2FTyIxwYosBRRZL12+U6RJlhbm1KFyKrLLT7qn4L5bEANUPKNw0DVVUsojHot8VodSs6wx0cU9qutTPmMxGpNi8YSvZWkwRvSOuQlEJo6IWRJB6TinqrqIWWtXNLFPKGQciUUz6jcSM5tl+Gg5SK9wnaLS10aiCfUFy4IpeEeJVRHI0j8imNW0a6u5RD6JxFhwZTI1BcagqP4oZ/IROlwqI261ASpaihZYpzsgYZVPXXVB3x2bVlccrL9W1LgwiwP7QHtGGc28DYI01wne7Xt9d0AShpf2hBJBrm9NKzXm1y/N/Nw3rd//9K7+z3+1/vHmn286AzINNsFZ4bWuuSE4zMi6YKpLk9DBe5gCt91hBxMJzPjjlBUx+VUihsPf3OHwDXL4a/IqSSChaB/6oYxGf9b1J4BKARcH4lcBT3Qnn2tzFuXo/r9/rmXLBFl8Wzj1cPgKQj1HC6NeX5u5Ld0CDUU8x7mMPwG2sqHD1ho7Y7CLXHHnrNNqndeKGbDdP0KZgSZArICm6GMFIGle2Cj1TZW6ihvOmQ4b5w4UjU2iY0mQxwUk38E8If43ysExj2FW3MH0D04FmI5ZlHLMGvIjhBoflxHgjuavAEvaBIkiBtVbOs1580cZ5Lg0kzahzrlMwVh4Mx3DjH8aCVaPYLIDg0L5VRjAQf6uX94oTCRGunET6U2VxzFXDTValw3Qlpfclq37hYTby+/RZAWyJWjffSKCXgy+ZUF9bJRa4rrut2DBHOucXRLTBduMv1QwOsDx0fQ7iiDzOiJ2diu6dyKiP0DRUG+MxSRXlN225F+IbOqnORQy/lTKS1t6r9VvnYb4WyIcWf1nnkPr4On5Xkvwvt1YPiM2noKkRtvtJ6FtfsVwGgRVrsyTGxJ4r3VxGgJvMX1sudeN/enIbee5JwnAptz9pyO3b1rYIa7X8Z4IABse/2TkXqtsd1rAiRS3x0PiBqf3uicyT7XYPZ6sVMkzwDAOfQZ/UxFPIp7J2A/04+atAr/rnkiZ8+h4FCa2iUCnd1rp734IkFQ32H7n4kS8vWT2iHLuVLM/1huainDnnYjzPwCAfaaOuy4sUdvd08pxx9T2vgn7rSzgRJz96C6AW1HyjPsY8mw7GJzI+s0jmLyI04zFAfdR9rWHC6dV2D9LbaQ2DznpzoviTkPUPdzK17/LZOKcmb0D4bn9zKxdBQa3E+M5tD+H9ufQ/vSC3FOWmvbTOGe0qcm+mehNs6n0dl7/nd5zMfzZnBt4I8Y8WAYRf6V7saN+v7pnsbeX8Dn+P8f/5/j/VCPh05T6cHQ0dzdX2439rXXfW+eF1S7B17qP/8Qu7KzgDqpb2ny44M/p4t7p4i454ltdAd3zbPdbWPLdZ+elyE9nlf9OUDw/ANrrFl6v/Q0Lva+M+AqkNm2KNAmcJKI5d5t0kMHPE+S9PCjgW/n00OJh+5aLh+4ueHjhObXh77X/RSNynJDjAc8Rd17oEwovnFCaS44jMueF4lmu4tSRcbR0bJbJQR3odcwVBxUBYQq/WRQ8C0UHLhzw3016JPGg7hLPzFw6/EqkmRn6Ax3FJwdHaUB2h35+++FtIwfkAjqylfGzF2uI1vMEIV7x9+K8EAXPNdqiO+YHT8TNUuevzudSYv2DZ2PwBLAIh06pLkN8udE2YRM+dFovNefHt8EHm9GGWc4D5ZzRAR5ty/B5y9hsmNeq0Cq2Tu9h8GYxmnkmouacKYGnyyF1TFKf3MYc495ZXeoWlpBVPFa9J/NVBJjObQPMrhqE7/Kye7vTinx9ICw4zoRnzpCC10vj0kPz/wHv53FoDaHPPZ7pg+EpP29k0pmyOaeT13RUNE/Phmke4Hn7c+tGPK0MAeS/3v39fxp0mLbsozGS4fL8a4kK+w7POmd0dtakPZoBrho1TaOmAHAne3bkH5r4/rS6b822Kin0jynxBpqr95poN+832ro/fcHf6BBj7XbpA2a9tkJWRdF/X8Y35NevTsA1hEGxhqBJdJe9djDlUbJrGb1444U9969A/nsxfnThAdYsmPrmjRSWX7SqyL+ngQFB8ERlL2d6X7EXPCy80pF3lnF6PYOiJHaLENGrZHXwMQR7jPyxjU9nUEVxe6QcckwM7AKoqM/sdaOLKp4+VY/LjGcs2sIE37+xGVwrefx2H853Co8vm9vdBV5pKo7vdgJvu01VUZ1H3IXrW+t8lOJbGzIbu9HtgoHbqyKV3IvzHdIX79rbASDM0vS1ZvHKMTtDmTdP7o0M5jUe1spiFc8njyXSA2NDU0+T/YUCcXcskOwHqXNimWSfOA8FCNefFfG8e3a7F6F2FevTxxBnp7OZ10btNk1zsUmvXCvWGHau3OuhbLtpVQXLfWU4EhwW0jvfIbMLmyomOEeT57HMppz7fDv2c9SAszk33BF5qrKjR4g8d+oSKvkgv0tmr2J6+AApHlL04UOCETTdO03ehqNTxcPy+wtx/wCzHwvcWlNeXXtaWl3Rd3cRHgOJtd1GOyGpZHvRKUGyb6vBV4WE/cZJ2rNQ7uFDiv3YIt1apPKt9xoeystBlIc8tBCqwnmOKdiXcSj3K4sxR8g9Nxcrlby+4qhJ6I7J/YalqB3l2ykuxVWzOrWrZPuyTz3vtkh1J0ShHxH4+L5fEQiQhgDeQgbCXrgNS1UJ6TgCbSKVJPfZubAjX+sX6u7IQjDT2LUf5c8OvaLX+TVx7Jf0OqtBnLFUDqNdHs5cMCebcufVLz+ZDR9BxIB+8DW/znfQtVh9LreKhHzsEMcHtrKs7a77q5PKPyLf2jWHbzAWAW9AM4tM+8KL3TRnNoqIOK6HnR/YBmMP+ftQLzqmH2Dwv+k3D/9SjtOAe+dcZTTU2e77XjrDsZIzf/VWeqBk0g8lvhBY82FtntEmQntohmucPNaumQeY3iMZ8R4d79kMs8euHcivYs4yvg4wmtye/g8YoVH8O7jRVv87Y3wxX5yZr0ny8VXW+42r2GG1xs8u+3w62gbwnjV7cpo1yKVNili7KxQ8uStYJD6tuaZ7owJ1yvgP6HIjExTdna2g1lr6HgkQgPG/A8r8PogEAAYNf6Bf/kbfR7EkLVKXDfpulQOh/3tAbRXoIWvRvabfFUeWsh9Nl3s0cLOuNLP+2Ai/Nf+gb8Czp/I3KGxNSSsANWBi7LzFmWWDx/MGPqL/94PbUgFNOubq09e8+Jm85PHZK6ot3uPvDdxXiw/6sSFdPZSoeWSZ0N7uyXgaFsW2LK3JqpS4rZqb1akrL8359uLdJlx380S95dSxFLAeTnk03taIhV7pb+WXrfiadMAIdIOG9Y0M/E8HdGyay8SUVZYeP3xJf9xUy+ZWrwIQnCh45bpMQcVIHXAVA1tr30yxpeA1mNZWZ6vY1nV/Ie4Ix0yEYcQXTPH7AtKu5JjbQ8S4/nCNf/4fKDLN5g==
    headers:
      User-Agent:
      - sentry-ruby/3.1.2
      Content-Type:
      - application/octet-stream
      X-Sentry-Auth:
      - Sentry sentry_version=5, sentry_client=raven-ruby/3.1.2, sentry_timestamp=1701293508,
        sentry_key=220b63fca88041809b887a91c5f3701d
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - nginx
      Date:
      - Wed, 29 Nov 2023 21:31:48 GMT
      Content-Type:
      - application/json
      Content-Length:
      - '41'
      Access-Control-Allow-Origin:
      - "*"
      Vary:
      - origin,access-control-request-method,access-control-request-headers
      Access-Control-Expose-Headers:
      - x-sentry-error,x-sentry-rate-limits,retry-after
      Cross-Origin-Resource-Policy:
      - cross-origin
      X-Envoy-Upstream-Service-Time:
      - '0'
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains; preload
      Via:
      - 1.1 google
      Alt-Svc:
      - h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
    body:
      encoding: UTF-8
      string: '{"id":"6e709a9b22ed47469e13d71ec76ac624"}'
  recorded_at: Wed, 29 Nov 2023 21:31:48 GMT
recorded_with: VCR 6.1.0
