---
http_interactions:
- request:
    method: post
    uri: https://<<SALESFORCE_HOST>>/services/oauth2/token
    body:
      encoding: US-ASCII
      string: grant_type=password&client_id=<<SALESFORCE_CLIENT_ID>>&client_secret=<<SALESFORCE_CLIENT_SECRET>>&username=<<SALESFORCE_USERNAME>>&password=<<SALESFORCE_PASSWORD>><<SALESFORCE_SECURITY_TOKEN>>
    headers:
      User-Agent:
      - Faraday v0.12.2
      Content-Type:
      - application/x-www-form-urlencoded
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Fri, 22 Mar 2019 23:23:04 GMT
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      Cache-Control:
      - no-cache,must-revalidate,max-age=0,no-store,private
      Set-Cookie:
      - BrowserId=-MgvvqQkQieFralvaQMNNA;Path=/;Domain=.salesforce.com;Expires=Tue,
        21-May-2019 23:23:04 GMT;Max-Age=5184000
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      X-Readonlymode:
      - 'false'
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
      Transfer-Encoding:
      - chunked
    body:
      encoding: UTF-8
      string: '{"access_token":"<<ACCESS_TOKEN>>","instance_url":"<<SALESFORCE_INSTANCE_URL>>","id":"https://<<SALESFORCE_HOST>>/id/00D0t0000000xVqEAI/005U00000066jl9IAA","token_type":"Bearer","issued_at":"1553296985592","signature":"yIrThIf0LNTybfwDdTo28pEd9q4am/kA8yrGqYIQfQQ="}'
    http_version: 
  recorded_at: Fri, 22 Mar 2019 23:23:05 GMT
- request:
    method: get
    uri: "<<SALESFORCE_INSTANCE_URL>>/services/data/v<<SALESFORCE_API_VERSION>>/query?q=%0A%20%20%20%20%20%20%20%20%20%20SELECT%20Listing__r.Id,%20Listing__r.Name,%20Listing__r.Status__c%0A%20%20%20%20%20%20%20%20%20%20FROM%20Application__c%0A%20%20%20%20%20%20%20%20%20%20WHERE%20Id%20=%20%27a0o0P00000GZazOQAT%27%0A%20%20%20%20%20%20%20%20"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.12.2
      Authorization:
      - OAuth <<ACCESS_TOKEN>>
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Fri, 22 Mar 2019 23:23:06 GMT
      Strict-Transport-Security:
      - max-age=31536002; includeSubDomains
      Public-Key-Pins-Report-Only:
      - pin-sha256="9n0izTnSRF+W4W4JTq51avSXkWhQB8duS2bxVLfzXsY="; pin-sha256="5kJvNEMw0KjrCAu7eXY5HZdvyCS13BbA0VJG1RSP91w=";
        pin-sha256="njN4rRG+22dNXAi+yb8e3UMypgzPUPHlv4+foULwl1g="; max-age=86400;
        includeSubDomains; report-uri="https://a.forcesslreports.com/hpkp-report/00D0t0000000xVqm";
      Expect-Ct:
      - max-age=0; report-uri="https://a.forcesslreports.com/Expect-CT-report/00D0t0000000xVqm";
      X-Robots-Tag:
      - none
      Cache-Control:
      - no-cache,must-revalidate,max-age=0,no-store,private
      Set-Cookie:
      - BrowserId=MdzdPVxIR3-2bA00vpBYkA;Path=/;Domain=.salesforce.com;Expires=Tue,
        21-May-2019 23:23:06 GMT;Max-Age=5184000
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Sforce-Limit-Info:
      - api-usage=4413/5000000
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
      Transfer-Encoding:
      - chunked
    body:
      encoding: UTF-8
      string: '{"totalSize":1,"done":true,"records":[{"attributes":{"type":"Application__c","url":"/services/data/v<<SALESFORCE_API_VERSION>>/sobjects/Application__c/a0o0P00000GZazOQAT"},"Listing__r":{"attributes":{"type":"Listing__c","url":"/services/data/v<<SALESFORCE_API_VERSION>>/sobjects/Listing__c/a0W0P00000GbyuQUAR"},"Id":"a0W0P00000GbyuQUAR","Name":"Partners
        Test Listing (do not modify) - Yellow Acres","Status__c":"Lease Up"}}]}'
    http_version: 
  recorded_at: Fri, 22 Mar 2019 23:23:06 GMT
- request:
    method: post
    uri: https://<<SALESFORCE_HOST>>/services/oauth2/token
    body:
      encoding: US-ASCII
      string: grant_type=password&client_id=<<SALESFORCE_CLIENT_ID>>&client_secret=<<SALESFORCE_CLIENT_SECRET>>&username=<<SALESFORCE_USERNAME>>&password=<<SALESFORCE_PASSWORD>><<SALESFORCE_SECURITY_TOKEN>>
    headers:
      User-Agent:
      - Faraday v0.12.2
      Content-Type:
      - application/x-www-form-urlencoded
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Fri, 22 Mar 2019 23:23:06 GMT
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      Cache-Control:
      - no-cache,must-revalidate,max-age=0,no-store,private
      Set-Cookie:
      - BrowserId=F96IfSAISLSd73UjErUSJw;Path=/;Domain=.salesforce.com;Expires=Tue,
        21-May-2019 23:23:06 GMT;Max-Age=5184000
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      X-Readonlymode:
      - 'false'
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
      Transfer-Encoding:
      - chunked
    body:
      encoding: UTF-8
      string: '{"access_token":"<<ACCESS_TOKEN>>","instance_url":"<<SALESFORCE_INSTANCE_URL>>","id":"https://<<SALESFORCE_HOST>>/id/00D0t0000000xVqEAI/005U00000066jl9IAA","token_type":"Bearer","issued_at":"1553296987476","signature":"N2y7vHxEf1ufIvvh0uXyXrl1/QUhMdT5EdVis8KqULU="}'
    http_version: 
  recorded_at: Fri, 22 Mar 2019 23:23:07 GMT
- request:
    method: get
    uri: "<<SALESFORCE_INSTANCE_URL>>/services/apexrest/LeasingAgentPortal/shortForm/Archive/a0o0P00000GZazOQAT"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v0.12.2
      Authorization:
      - OAuth <<ACCESS_TOKEN>>
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 404
      message: Not Found
    headers:
      Date:
      - Fri, 22 Mar 2019 23:23:08 GMT
      Strict-Transport-Security:
      - max-age=31536002; includeSubDomains
      Public-Key-Pins-Report-Only:
      - pin-sha256="9n0izTnSRF+W4W4JTq51avSXkWhQB8duS2bxVLfzXsY="; pin-sha256="5kJvNEMw0KjrCAu7eXY5HZdvyCS13BbA0VJG1RSP91w=";
        pin-sha256="njN4rRG+22dNXAi+yb8e3UMypgzPUPHlv4+foULwl1g="; max-age=86400;
        includeSubDomains; report-uri="https://a.forcesslreports.com/hpkp-report/00D0t0000000xVqm";
      Expect-Ct:
      - max-age=0; report-uri="https://a.forcesslreports.com/Expect-CT-report/00D0t0000000xVqm";
      X-Robots-Tag:
      - none
      Cache-Control:
      - no-cache,must-revalidate,max-age=0,no-store,private
      Set-Cookie:
      - BrowserId=Xw7pLNNISHiZr3NsonVsuQ;Path=/;Domain=.salesforce.com;Expires=Tue,
        21-May-2019 23:23:08 GMT;Max-Age=5184000
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      Transfer-Encoding:
      - chunked
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Fri, 22 Mar 2019 23:23:08 GMT
- request:
    method: post
    uri: https://<<SALESFORCE_HOST>>/services/oauth2/token
    body:
      encoding: US-ASCII
      string: grant_type=password&client_id=<<SALESFORCE_CLIENT_ID>>&client_secret=<<SALESFORCE_CLIENT_SECRET>>&username=<<SALESFORCE_USERNAME>>&password=<<SALESFORCE_PASSWORD>><<SALESFORCE_SECURITY_TOKEN>>
    headers:
      User-Agent:
      - Faraday v0.12.2
      Content-Type:
      - application/x-www-form-urlencoded
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Fri, 22 Mar 2019 23:23:08 GMT
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      Cache-Control:
      - no-cache,must-revalidate,max-age=0,no-store,private
      Set-Cookie:
      - BrowserId=CSvTkx1DRiefBIDta-gzbQ;Path=/;Domain=.salesforce.com;Expires=Tue,
        21-May-2019 23:23:08 GMT;Max-Age=5184000
      Expires:
      - Thu, 01 Jan 1970 00:00:00 GMT
      X-Readonlymode:
      - 'false'
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
      Transfer-Encoding:
      - chunked
    body:
      encoding: UTF-8
      string: '{"access_token":"<<ACCESS_TOKEN>>","instance_url":"<<SALESFORCE_INSTANCE_URL>>","id":"https://<<SALESFORCE_HOST>>/id/00D0t0000000xVqEAI/005U00000066jl9IAA","token_type":"Bearer","issued_at":"1553296989592","signature":"443r5o+VJacag7aZBnZf591BEGDSRB3DaG2qRGtbLU0="}'
    http_version: 
  recorded_at: Fri, 22 Mar 2019 23:23:09 GMT
recorded_with: VCR 4.0.0
